version: '2.3'

services:
  redis:
    restart: always
    #image: sameersbn/redis:latest
    image: redis:6.2.6
    command:
    - --loglevel warning
    volumes:
    - ./redis:/var/lib/redis:Z

  postgresql:
    restart: always
    #image: sameersbn/postgresql:10
    image: sameersbn/postgresql:12-20200524
    volumes:
    - ./postgresql:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    #- DB_EXTENSION=pg_trgm
    - DB_EXTENSION=pg_trgm,btree_gist

  gitlab:
    restart: always
    #image: sameersbn/gitlab:9.5.5
    image: sameersbn/gitlab:14.6.0
    depends_on:
    - redis
    - postgresql
    ports:
    - "${GITLAB_PORT}:80"
    - "${GITLAB_SSH_PORT}:22"
    - "${GITLAB_SSL_PORT}:443"
    volumes:
    - ./gitlab:/home/git/data:Z
    env_file: .env

