version: '2'

services:
  redis:
    restart: always
    #image: sameersbn/redis:latest
    image: redis:5.0.9
    command:
    - --loglevel warning
    volumes:
    - ./redis:/var/lib/redis:Z

  postgresql:
    restart: always
    #image: sameersbn/postgresql:10
    image: sameersbn/postgresql:11-20200524
    volumes:
    - ./postgresql:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    #- DB_EXTENSION=pg_trgm
    - DB_EXTENSION=pg_trgm,btree_gist

  gitlab:
    restart: always
    #image: sameersbn/gitlab:9.5.5
    image: sameersbn/gitlab:13.3.4
    depends_on:
    - redis
    - postgresql
    ports:
    - "10080:80"
    - "10022:22"
    - "10443:443"
    volumes:
    - ./gitlab:/home/git/data:Z
    env_file: .env

